"use strict";
console.log("SELF INTROIDUCTION AND PORT FOLIO OF SAAD QURESHI");
const Name = ("My Name Is Saad Qureshi");
let Age = 21;
let Confirm = true;
let qualification = ("matriculation");
let courses = ("GEN AI ENGINEER AND WEB 3.0 DEVOLPER");
let languages = ["URDU", "ENGLISH"];
let family = 6;
let freinds = ["NEHAL", "LARAIB", "HUNAIN", "SAMAR", "FAISAL"];
console.log("\n what is your name ? : \n");
console.log(Name);
console.log("\n what is your age ? \n");
console.log(`my age is =>${Age}`);
console.log("\n what is your qualification \n ");
console.log(`I Passed ${qualification} in bio science from sindh board `);
console.log("\n which courses do you have to know ? \n");
console.log(`iam ${courses} software enginner`);
console.log("\n how many languages do you speak ? :\n");
console.log(`i speak ${languages}`);
console.log("\n how many persons are in your family ? :\n");
console.log(`\n we are ${family} persons \n`);
console.log(`\n this is my freinds : ${freinds} \n`);
